config/routes.rb
Rails.application.routes.draw do

  get 'playlists/index'

  get 'profiles/show'
  get 'api/show'

  devise_for :users, controllers: {registrations: 'users/registrations'}
  
  resources :users, only: [:index] do
    resource :profile, only: [:show]
    resources :playlists, except: [:new, :edit]#, defaults: { format: 'json' }
  end
  
  post 'playlists/add_track' => 'playlists#add_track', as: :playlist_add_track

  root 'api#show'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	belongs_to :user
	has_many :tracks

	validates :title, :user_id, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/track.rb
class Track < ActiveRecord::Base
	belongs_to :playlist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_one :profile
  has_many :playlists
  has_many :tracks, through: :playlists

  accepts_nested_attributes_for :profile

  before_create :set_default_role

  private
  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
	def show
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper :entries
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
  	@all_playlists = current_user.playlists.all

  	respond_to do |format|
  	  format.json { render :json => @all_playlists }
  	end
  end

  def show
    @user = User.find(params[:user_id])
    @playlist = @user.playlists.find(params[:id])
  end

	# take a playlist_id and track json object (serialized)
	# create that track in the db (if it doesn't exist?)
  def add_track
    new_track = Track.new(track_params)
    if new_track.save
      render :json => new_track
    else
      render :json => new_track.errors.full_messages
    end
  end

  private
  def track_params
    params.require(:track).permit(:sc_track_id, :title, :artwork_url, :sc_user_id, :playlist_id, :username)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user_id = params[:user_id]
  	@user = User.find(@user_id)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  end

  def edit
  end

  def index
    @all_users = User.order(:created_at)
  end

  def update
  end

  def destroy
  end

  def show
  end

  def new
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
	def entry
    return Entry.find(params[:id])
  end

  def owned_by_current_user?
    return current_user == entry.user
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
	<a id="logo" href="/">Next.fm</a>
	<nav>
		<!-- buttons change if logged in -->
		<%if user_signed_in? %>
			<li><%= link_to "My Playlists", user_playlist_path(current_user, 1)  %></li>
			<li><%= link_to "Log out", destroy_user_session_path, method: :delete  %></li>

		<% else %>
			<li><%= link_to "Sign in", new_user_session_path  %></li>
			<li><%= link_to "Create an account", new_user_registration_path  %></li>
		<% end %>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Next.fm</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<main>
		<%= yield %>
	</main>

	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js"></script>
	<script src="http://connect.soundcloud.com/sdk.js"></script>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>